### ISSUE TITLE
cloud_ip.inspect fails

### ISSUE THREAD

**Issue by robd** [fog/fog-brightbox#17]
Calling 'cloud_ip.inspect' fails because formatador is checking for, and calling, the map method:

    .bundle/gems/ruby/1.9.1/gems/fog-brightbox-0.7.1/lib/fog/brightbox/models/compute/cloud_ip.rb:32:in `map': wrong number of arguments (0 for 1) (ArgumentError)
    .bundle/gems/ruby/1.9.1/gems/fog-core-1.29.0/lib/fog/formatador.rb:87:in `inspect_object'

But in this case, the `map` method is overridden and actually modifies the cloud_ip. Fortunately, it fails and nothing is modified.

Not sure what the correct thing to do here is? Perhaps rename to `map_to` or `map!` and deprecate `map`? PR for formatador to check the arity? Or override the `inspect` method in `CloudIp`?

In general it would help if the methods which actually made changes ended in `!` Not sure if this breaks the normal naming convention of fog, but this would make it clear when you were doing a safe 'read' type operation (with no exclamation mark), or more dangerous mutation operations which need more care.

**Comment by tokengeek** [comment]
Thanks for reporting this.

I had spotted this and have been tracking it in our internal bug tracker.

You've actually dug into the issue a bit more and I still haven't decided on the best approach just yet.

Fog's naming convention, even for creates and updates is without the `!`. It set out with Rails like, CRUD operations so the thinking was `create` will create and actually make changes.

I seen Ruby's convention for `!` argued a few different ways. Mainly it either needs to alter the receiver _unless it obviously does anyway_ or Rails behaviour (`save` still persists but `save!` raises with errors).

Seems AWS has gone with an association style setter and use `Address#server=` for the same.

Part of me thinks it's a Formatador issue. Given a Object which is not a collection, they test for `map` and not `each` or Enumerable. It was introduced after `fog-core 1.24.0` just due to that implementation detail.

If they were assembling the errors, using `each` or `inject` this wouldn't be a problem.

Then again the issue is likely to occur again at some point.

I think I'll report the issue in `fog-core` but also look to deprecate `map` for `server=` and drop it in the next major release.

**Comment by robd** [comment]
> Part of me thinks it's a Formatador issue. Given a Object which is not a collection, they test for map and not each or Enumerable. It was introduced after fog-core 1.24.0 just due to that implementation detail.

I tend to agree with you here; it's a bit dodgy for them to use duck typing and go around calling map on any object they find knocking around. Checking Enumerable would be better.

> Then again the issue is likely to occur again at some point.

Yes I think for safety it might be wise to rename the method anyway, in case someone calls map incorrectly due to a programming error or something.

Re method name, personally, I don't like using `obj.whatever=` for mutating methods either! For me, at least, it's not clear to me that this would go off and update something on the server. I think if the convention used throughout the rest of the brightbox fog API is not to use `whatever=`, it would be best not to do something different in this one case.

Maybe a name like `cloud_ip.update_mapping` or `cloud_ip.replace_mapping`?

**Comment by tokengeek** [comment]
Well `CloudIp` is a fog "model" as opposed to a request.

Models were based on Rails CRUD and more importantly should (but don't) behave consistently between providers implementations.

So the process should really be something like:

```
@server = Server.new
@server.image = @image
@server.save
@cloud_ip.server = @server
@cloud_ip.save
```

This should behave the same for AWS, Brightbox or any provider so I need to discuss this with the rest of the core team when we get the chance to standardise the models.

Because the AWS (`Address`) implementation should do the same thing and both should support the use case that we can point Cloud IPs at load balancers, not just servers.

Due to the way the models were originally created and with a lack of a specification a lot of models ended up read-only and need updating with requests. `#save` raises instead of attempting an update (or in this case a `map`).

**Comment by robd** [comment]
I think the syntax you propose is very clear from a rails programmer's point of view, makes it  clear that the save methods will actually make the REST calls and do the work. 

I can imagine that it is a big effort to get consistency across all of the different cloud providers, I guess this may be an ongoing effort. But in the meantime, I think fix you propose for https://github.com/fog/fog-core/issues/138 to Formatador should fix the immediate problem. Thanks for your help with this!

**Comment by tokengeek** [comment]
For the record, critical errors were introduced in `fog-core` versions `1.26.0 - 1.29.0` which caused problems here.

Limiting applications to `1.25.0` or the next release should resolve this issue.

**Comment by geemus** [comment]
@tokengeek thanks for clarifying.
