### ISSUE TITLE
Could you please add mocks for tests?

### ISSUE THREAD

**Issue by Hirurg103** [fog/fog-brightbox#40]
When I try to mock fog brightbox in rspec tests with 

```ruby
Fog.mock!

fog_credentials = {
  provider: "Brightbox",
  brightbox_client_id: 'xxx',
  brightbox_secret: 'yyy'
}

CarrierWave.configure do |config|
  config.fog_credentials = fog_credentials
end

connection = ::Fog::Storage.new(fog_credentials)
connection.directories.create(key: ENV['UPLOADS_DIRECTORY'])

```

and then start to run tests I get

```
~/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-core-1.45.0/lib/fog/core/mock.rb:32:in `not_implemented': Contributions welcome! (Fog::Errors::MockNotImplemented)
	from ~/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-core-1.45.0/lib/fog/core/service.rb:306:in `put_container'
	from ~/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fog-brightbox-0.14.0/lib/fog/brightbox/models/storage/directory.rb:44:in `save'
...
```

So I have to stub my tests with `AWS` provider which is not correct

Could you add mocks for storage please? Thank you!

**Comment by tokengeek** [comment]
Hi @Hirurg103 

Orbit is actually an implementation of Openstack Swift which provides some of the Fog mocked interface.

The reason we didn't implement `Fog::Brightbox::Storage::Mock` was that it was a pretty big implementation to do, as it would have been for our `Compute` service.

The idea of being able to switch between a real and mocked backend was good but the implementation created a lot of work since it created two versions of a lot of the code. That meant parallel code paths, parallel bugs and an in-memory data store to keep track of changes.

Back-end changes needed keeping in sync with the real systems and it was difficult enough keeping VCR based tests up to date with the option of re-recording them rather than a manually written implementation.

When I have looked at this on occasion it gets complex very quickly. Multiple authentication schemes, account limits, emulating network delays and there were dozens of cases I could create mocked tests that failed in real life, giving a false sense of security.

So rather than than `Fog.mock!` I would recommend, depending on your test case, either `WebMock` to test the HTTP layer or stubbing the `Fog` classes themselves.

Neither of them are helpful if it is just to explore the API on the console though.

So I'm going to close this as I can't see us having the schedule to do this anytime soon with other things on the backlog.
