### ISSUE TITLE
Need to authenticate every time when generating temporary url

### ISSUE THREAD

**Issue by Hirurg103** [fog/fog-brightbox#41]
We are experiencing problems with generating temporary url for a file in our carrierwave uploader. The code looks the following way:

```ruby
def temp_url
  connection.get_object_https_url(fog_directory, version.path, expire_in = 1.day.from_now)
end
```

where `connection` is an instance of `Fog::Storage::Brightbox`. When generating `temp_url` it fails with `NoMethodError: undefined method 'path' for nil:NilClass`

I looked into the source code and found out that it fails [there](https://github.com/fog/fog-brightbox/blob/21d2a2f7cd11bdbe81ff3571754ec60031d36378/lib/fog/brightbox/requests/storage/get_object_https_url.rb#L47). The problem is that `management_url` is `nil`

I investigated further and found out that `storage_management_url` is being set in the [Fog::Storage::Brightbox#authenticate](https://github.com/fog/fog-brightbox/blob/21d2a2f7cd11bdbe81ff3571754ec60031d36378/lib/fog/brightbox/storage.rb#L107-L118)

so if I change `temp_url` to

```ruby
def temp_url
  connection.authenticate
  connection.get_object_https_url(fog_directory, version.path, expire_in = 1.day.from_now)
end
```
it doesn't fail with exception

Another way is to configure `brightbox_storage_management_url` manually
```ruby
CarrierWave.configure do |config|
  config.fog_credentials = {
    provider: "Brightbox",
    ...
    brightbox_storage_management_url: "https://orbit.brightbox.com/v1/acc-12345" 
  }
end
```

I think that making authenticate request every time we generate temporary url for a document is not a good practice. The only problem with setting `brightbox_storage_management_url` is that we get warning from the fog library

```
[fog][WARNING] Unrecognized arguments: brightbox_storage_management_url
```

Could you raise a clear exception when `brightbox_storage_management_url` is not configured?
Could you fix that `Unrecognized arguments` fog warning?

**Comment by tokengeek** [comment]
Thanks for the detailed bug report. I'll look into it

**Comment by tokengeek** [comment]
@Hirurg103 Can you confirm the versions of `carrierwave`, `fog`, `fog-core` and `fog-brightbox` you are using?

I've been testing with `fog-brightbox v0.14.0` and `fog-core v1.44.3`.

There is an existing error that should be raised when the management URL is not available.

Going with an absolutely minimal configuration, I can get the expected `Fog::Brightbox::Storage::ManagementUrlUnknown` error. Without client ID and secret, `ArgumentError` is raised as they are required.

```ruby
> Fog::Brightbox::Storage::Connection.new(Fog::Brightbox::Storage::Config.new(Fog::Brightbox::Config.new(provider: "Brightbox", brightbox_client_id: "cli-12345", brightbox_secret: "1234")))
Fog::Brightbox::Storage::ManagementUrlUnknown: Fog::Brightbox::Storage::ManagementUrlUnknown
from /home/paul/code/fog-brightbox/lib/fog/brightbox/storage/connection.rb:11:in `initialize'
```
Even moving a bit higher up, creating the provider with values off disk works and then, calling `#connection` gives me the same error.


```ruby
> Fog::Storage.new(provider: "Brightbox")
=> #<Fog::Storage::Brightbox::Real:33969200 @config=#<Fog::Brightbox::Config:0x00000000040ca838 @options={:brightbox_client_id=>"cli-12345", :brightbox_secret=>"12345", :brightbox_temp_url_key=>"xx"}> @temp_url_key="xx">
> Fog::Storage.new(provider: "Brightbox").connection
Fog::Brightbox::Storage::ManagementUrlUnknown: Fog::Brightbox::Storage::ManagementUrlUnknown
from /home/paul/code/fog-brightbox/lib/fog/brightbox/storage/connection.rb:11:in `initialize'
```

Directly creating an instance and calling `#create_temp_url` is the nearest I've come to recreate the issue but with `nil` the error is on the previous line since you can't `dup` `NilClass`

```ruby
> Fog::Storage::Brightbox.new.create_temp_url "my_container", "uploads/test", Time.now, "GET"
TypeError: can't dup NilClass
from /home/paul/code/fog-brightbox/lib/fog/brightbox/requests/storage/get_object_https_url.rb:46:in `dup'
```

So I can't recreate the exact issue at the moment since `NilClass#path` shouldn't being called. It should have failed on the previous line with `NilClass#dup`

I even added a test case to confirm the problem on a connection and it immediately passed without needing a fix.

----

So the configuration seems to be in an intermediate state to get past the checks that are already in place.

If you can supply the library versions I'll try to narrow down how CarrierWave is passing in the configurations and try to see if the recent work on `fog v2.0` has changed anything.

**Comment by Hirurg103** [comment]
Hello @tokengeek,

we are using the following gem versions
```
carrierwave (1.2.2)
fog (1.41.0)
fog-core (1.45.0)
fog-brightbox (0.14.0)
```

**Comment by Hirurg103** [comment]
@tokengeek 

we are getting `connection` from the storage in our uploader

```ruby
class DocumentUploader

  def temp_url
    connection.get_object_https_url(fog_directory, version.path, expire_in = 1.day.from_now)
  end

  private def connection
    self.send(:storage).connection
  end

end
```

**Comment by tokengeek** [comment]
@Hirurg103 Thanks that helps a lot.

So what has helped confuse matters (and my testing) is that `CarrierWave::Storage::Fog#connection` actually returns the _service_ (`Fog::Storage::Brightbox::Real`) and not a connection.

`#get_object_https_url` is a method on the service but it does not require a HTTP request so the connection (which is lazy loaded) does not run.

So when you are calling `(Service)#authenticate` it is doing a HTTP request and as per Swift recommendations (IIRC) it is setting the management URL then.

So if you were to make any other call that triggered a connection, you would get the error.

```ruby
class DocumentUploader < CarrierWave::Uploader::Base
  storage :fog

  def service
    # Returns the Fog::Storage::Brightbox service
    self.send(:storage).connection
  end

  def connection
    service.connection
  end

  def temp_url
    service.get_object_https_url(...)
  end
end

> uploader = DocumentUploader.new
> uploader.connection
Fog::Brightbox::Storage::ManagementUrlUnknown: Fog::Brightbox::Storage::ManagementUrlUnknown
        from /home/paul/code/carrierwave/vendor/bundle/ruby/2.1.0/gems/fog-brightbox-0.14.0/lib/fog/brightbox/storage/connection.rb:11:in `initialize'
        from /home/paul/code/carrierwave/vendor/bundle/ruby/2.1.0/gems/fog-brightbox-0.14.0/lib/fog/brightbox/storage.rb:84:in `new'
...
> uploader.service
=> #<Fog::Storage::Brightbox::Real ...>
```

So as you said, the real problem (which I think I realised at the time) is here: 

https://github.com/fog/fog-brightbox/blob/21d2a2f7cd11bdbe81ff3571754ec60031d36378/lib/fog/brightbox/requests/storage/get_object_https_url.rb#L45-L46

And *assumes* is the mistake because you can call this out of sequence.

I'll try to get fixes into place today.

**Comment by tokengeek** [comment]
@Hirurg103 This should be fixed in `fog-brightbox v0.15.0` which I have just released.

Can you test and confirm it now works? Thanks.

**Comment by Hirurg103** [comment]
Hello @tokengeek 

thank you a lot for the fix!

After the upgrade to `v.0.15.0`
```
Fog::Brightbox::Storage::ManagementUrlUnknown: Storage must be instantiated with the :brightbox_storage_management_url or you must authenticate first
```

 if `brightbox_storage_management_url` is not set. Also 

```
[fog][WARNING] Unrecognized arguments: brightbox_storage_management_url
```
has disappeared

> So what has helped confuse matters (and my testing) is that CarrierWave::Storage::Fog#connection actually returns the service (Fog::Storage::Brightbox::Real) and not a connection.

Is this a problem that we are using `Fog::Storage::Brightbox::Real` to generate object https url inside our carrierwave uploader?

**Comment by tokengeek** [comment]
Glad to hear it is fixed.

Using `get_object_https_url` on the `Fog::Storage::Brightbox` service is the *correct* API to get a temporary URL, so I don't believe there is an issue there.

The main problem was Fog and Carrierwave using "connection" with slightly different meanings.

So I tested the wrong class to begin with and you never though to call `connection.connection` to eager load the connection (and find the missing configuration setting).

I don't think you need that anymore in which case you can leave `DocumentUploader#connection` (CarrierWave name) which was private anyway as is or rename to be `#service` (Fog name) whichever is clearest to your team.

**Comment by Hirurg103** [comment]
Great, thank you for the help @tokengeek
