### ISSUE TITLE
Broken dependency

### ISSUE THREAD

**Issue by craigedmunds** [fog/fog-brightbox#56]
Hello. We've spotted a problem with your dependencies - dry-inflector has updated the version of ruby it requires to 2.6 whilst moving from 0.2.0 to 0.2.1. 

spec.required_ruby_version = ">= 2.6.0"

https://github.com/dry-rb/dry-inflector/compare/v0.2.0...v0.2.1#diff-3704ec4dbc45bef5694c0137b84246fd462a0029c828df6113dd16039e1879dbR29

**Comment by tokengeek** [comment]
Thanks for letting us know.

They actually added a "Ruby >= 2.4" requirement to `v0.2.0` in October 2019 but when the Github actions ran 2 months ago for [v1.4.1](https://github.com/fog/fog-brightbox/tree/v1.4.1) it used `v0.1.2` in some cases and so no problems were reported by any of the Ruby 2.0 to 2.3 tests.

https://github.com/fog/fog-brightbox/actions/runs/767094790

The older versions picked up 0.1.2 and the newer ones 0.2.0. Possibly due to Github magic to account for the older Rubies and Bundler issues or a cached set of gems.

In which context are you seeing this as a problem? Your own application or via `fog`?

Since `fog-brightbox` is primarily intended as a library for use by client applications, it would probably be easiest fixed in a `Gemfile` to limit the version of `dry-inflector` used rather than add a dependency for older versions of Ruby blocking newer versions.

**Comment by tokengeek** [comment]
Looking at the diff, there are some fixes between `dry-inflector` v0.1.2 and v0.2.0 but not in the `underscore` function we use it for.

https://github.com/dry-rb/dry-inflector/compare/v0.1.2...v0.2.0

But if we add a dependency to `fog-brightbox` for "< 0.2" then potentially we'd prevent anyone using the other method with the fixes in their own application or clashing with other dependencies which is why we tend to leave them open ended.

**Comment by tokengeek** [comment]
@craigedmunds Have you been able to work around this?

Without more details about the context I don't think pinning a dependency will help longer term as it will just need unpinning so I am planning on closing the issue since options are limited.

But with the note that it can be resolved in older versions of Ruby by specifying the `dry-inflector` version to `v0.1.2` in `Gemfile` in any applications getting caught by this.

**Comment by tokengeek** [comment]
Closing due to lack of response.
